version: "3.2"
services:
 redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "56379:56379"
    volumes:
     - ./redis-data:/var/lib/redis
     - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4
 app: 
    build: .
    command: ./bin/server
    ports:
      - "5000:5000"
    environment:
     - API_HOST=localhost
     - API_PORT=5000
     - REDIS_HOST=172.28.1.4
     - REDIS_PORT=6379
    depends_on:
      - redis  
    networks:
      - node_net
# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
